name: manual

on:
  workflow_dispatch:
    inputs:
      logLevel:
        name: 'Log level'
        required: true
        default: 'warning'

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"

